// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import MessagerController from './messanger_controller'
import MessangerBoardController from './messanger_board_controller'

application.register("hello", HelloController)
application.register("messanger",  MessagerController)
application.register("messanger_board", MessangerBoardController)
