// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import MessagerController from './messanger_controller'
import MessangerBoardController from './messanger_board_controller'
import UserController from './user_controller'
import ProgramController from './program_controller'
import ExerciseController from './exercise_controller'
import WorkoutController from './workout_controller'
import DataTableController from './datatable_controller'
import programCreatorController from './program_creator_controller';

application.register("hello", HelloController)
application.register("messanger",  MessagerController)
application.register("messanger_board", MessangerBoardController)
application.register("user", UserController)
application.register("program", ProgramController)
application.register("exercise", ExerciseController)
application.register("workout", WorkoutController)
application.register('datatable', DataTableController)
application.register("programCreator", programCreatorController)
